FROM mcr.microsoft.com/dotnet/sdk:10.0

ENV ASPNETCORE_ENVIRONMENT='Development'
ENV ASPNETCORE_URLS='http://+:8080'
ENV CORS_DOMAIN='http://localhost:9080'
ENV DOTNET_USE_POLLING_FILE_WATCHER=1

RUN curl -sSL https://aka.ms/getvsdbgsh | /bin/sh /dev/stdin -v latest -l /vsdbg

RUN dotnet tool install --global dotnet-ef
ENV PATH="$PATH:/root/.dotnet/tools"

# Copy all source code and restore NuGet packages
WORKDIR /opt/app-root/src
COPY ../api ./api
