export interface ExhibitSubmissionModel {
  appearanceId: string,
  appearanceDateTime: string,
  shortDate: string,
  appearanceSequenceNumber: string,
  appearanceReasonCode: string,
  courtListType: string,
  fileNumberText: string,
  locationId: string,
  locationNameText: string,
  roomCode: string,
  roomText: string,
  accusedName: string,
  accusedDOB: string,
  officerNumber: string,
}