<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Queries\**" />
    <Compile Remove="Validations\**" />
    <EmbeddedResource Remove="Queries\**" />
    <EmbeddedResource Remove="Validations\**" />
    <None Remove="Queries\**" />
    <None Remove="Validations\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Next" Version="4.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.3" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.16.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CES.Entities\CES.Entities.csproj" />
    <ProjectReference Include="..\jc-interface-client\jc-interface-client.csproj" />
  </ItemGroup>

</Project>
