#!/bin/bash
export MSYS_NO_PATHCONV=1
set -e

SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd)"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-csb-exhibit-submissions}"

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage() {
  cat <<-EOF

  Usage: $0 {start|debug|stop|build|rm|down}

  Options:

  build - Build the docker images for the project.
          You need to do this first, since the builds require some s2i builds.
          You can build individual components as shown below, components that have dependencies
          will have these dependencies built too.  By default all components are built.

          Examples:
          - Build everything:
            $0 build
          - Build the api only:
            $0 build api
          - Build the web only:
            $0 build web
          - Build the nginx proxy only:
            $0 build nginx

          Containers:
            - nginx
            - api
            - web

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yaml file.
          Example:
            $0 start

  debug - Used for local development that enables hot reloading for BE.
          Creates the application containers from the built images
          and starts the services based on the docker-compose.yaml file.
          Example:
            $0 debug

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.

  down | rm - Brings down the services and removes the volumes (storage) and containers. Destructive.
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Default Settings:
# -----------------------------------------------------------------------------------------------------------------
RUNTIME_CONTAINERS="nginx web api db"
DEBUG_CONTAINERS="nginx web api db"
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
build-all() {
  build-nginx
  build-web
  build-api
}

build-nginx() {
  #
  # nginx reverse proxy
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building nginx reverse proxy image using docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t "${COMPOSE_PROJECT_NAME}-nginx" \
    -f './nginx-proxy/Dockerfile' './nginx-proxy'
  echo -e "===================================================================================================="
}

build-web() {
  #
  # web-dev
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building the ${COMPOSE_PROJECT_NAME}-web (dev) image using Docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t "${COMPOSE_PROJECT_NAME}-web" \
    --build-arg NODE_VERSION=22 \
    --build-arg VITE_PORT=8080 \
    --build-arg WEB_SRC='./web' \
    -f './web/Dockerfile.dev' '..'
  echo -e "===================================================================================================="
}

build-api() {
  #
  # api
  #
  echo -e "\n\n===================================================================================================="
  echo -e "Building api image using docker ..."
  echo -e "----------------------------------------------------------------------------------------------------"
  docker build \
    -t "${COMPOSE_PROJECT_NAME}-api" \
    -f './api/Dockerfile.dev' '..'
  echo -e "===================================================================================================="
}

configureEnvironment () {

  if [ -f .env ]; then
    echo -e "\nLoading environment variables from .env ...\n"
    source .env
  fi

  for arg in $@; do
    case "$arg" in
      *=*)
        export ${arg}
        ;;
    esac
  done

  # Default database startup parameters
  export POSTGRESQL_DATABASE=${POSTGRESQL_DATABASE:-cesdb}
  export POSTGRESQL_USER=${POSTGRESQL_USER:-postgres}
  export POSTGRESQL_PASSWORD=${POSTGRESQL_PASSWORD:-postgres}

  # Default connection string
  export DatabaseConnectionString=${DatabaseConnectionString:-"Host=db;Port=5432;Database=${POSTGRESQL_DATABASE};Username=${POSTGRESQL_USER};Password=${POSTGRESQL_PASSWORD};"}

  # Default API startup parameters
  export ASPNETCORE_URLS=${ASPNETCORE_URLS:-http://+:8080}
  export CORS_DOMAIN=${CORS_DOMAIN:-http://localhost:9080}
}

getStartupParams() {
  CONTAINERS=""
  ARGS=""

  for arg in $@; do
    case "$arg" in
      *=*)
        # Skip it
        ;;
     -*)
        ARGS+=" $arg";;
      *)
        CONTAINERS+=" $arg";;
    esac
  done

  if [ -z "$CONTAINERS" ]; then
      if [ -z "$DEBUG_MODE" ]; then
        CONTAINERS="$RUNTIME_CONTAINERS"
      else
        CONTAINERS="$DEBUG_CONTAINERS"
      fi
  fi

  echo ${ARGS} ${CONTAINERS}
}

toLower() {
  echo $(echo ${@} | tr '[:upper:]' '[:lower:]')
}

functionExists() {
  (
    if [ ! -z ${1} ] && type ${1} &>/dev/null; then
      return 0
    else
      return 1
    fi
  )
}

deleteVolumes() {
  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  echo "Stopping and removing any running containers ..."
  docker-compose down -v

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern} | cat)

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} | xargs docker volume rm
  else
    echo "No project volumes exist."
  fi

  echo "Removing build cache ..."
  rm -Rf ../api/CES.API/bin
  rm -Rf ../api/CES.API/obj
  rm -Rf ../web/node_modules
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null
COMMAND=$(toLower ${1})
shift

case "$COMMAND" in
  start)
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;
  debug)
    export DEBUG_MODE=1
    _startupParams=$(getStartupParams $@)
    configureEnvironment $@
    docker-compose up ${_startupParams}
    ;;
  stop)
    docker-compose stop
    ;;
  rm|down)
    configureEnvironment
    deleteVolumes
    ;;
  build)
    buildImage=$(toLower ${1})
    shift || buildImage=all
    buildImage=$(echo ${buildImage} | sed s~^vcr-~~)
    case "$buildImage" in
      *=*)
        buildImage=all
        ;;
    esac

    if functionExists "build-${buildImage}"; then
      eval "build-${buildImage}"
    else
      echo -e "Error:\nThe build function, build-${buildImage}, does not exist.  Please check your build parameters and try again.\nUse '-h' to get full help details."
      exit 1
    fi
    ;;
  *)
    usage
esac

popd >/dev/null
