#!/usr/bin/env bash
# Installs Source-to-Image (s2i) tooling.
S2I_VERSION="source-to-image-v1.4.0-d3544c7e-linux-amd64.tar.gz"

wget "https://github.com/openshift/source-to-image/releases/download/v1.4.0/${S2I_VERSION}" \
    -O "/tmp/${S2I_VERSION}"
tar -xzf "/tmp/${S2I_VERSION}" -C /usr/local/bin
rm "/tmp/${S2I_VERSION}"

echo "s2i installed: $(s2i version)"
